language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 7.1
    - 7.2
    - nightly

install:
    - travis_retry composer install

script: ./vendor/bin/phpunit